version: '3'

volumes:
  lotus-data:
    driver: local

services:
# Database
  mysql-database:
    image: mysql:5.7.22
    volumes:
      - lotus-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

# Web / API
  lotus-web:
    image: centraldofretecom/ambientum-php:7.3-nginx
    volumes:
      - .:/var/www/app
      - .env:/var/www/app/.env
    ports:
      - "8010:8080"
    environment:
      - XDEBUG_CONFIG="remote_host=localhost remote_port=9000"
      - XDEBUG_ENABLED=true
      - PHP_IDE_CONFIG=serverName=xdebug-docker
    links:
      - mysql-database
